services:
  - name: docker:dind
    entrypoint: ["env", "-u", "DOCKER_HOST"]
    command: ["dockerd-entrypoint.sh"]

stages:
  - build

variables:
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

Build API DEV:
  stage: build
  only:
    - develop
  allow_failure: false
  image: docker:latest
  services:
    - docker:19.03.13-dind
  before_script:
    - export ENV_FILE=$ENV_DEV
    - export DOCKER_TAG=$CI_COMMIT_SHORT_SHA
    - docker login -u ${CI_REGISTRY_USER} -p ${CI_REGISTRY_PASSWORD} ${CI_REGISTRY}
  script:
    - cp "${ENV_FILE}" .env
    - docker build -t ${CI_REGISTRY_IMAGE}:${DOCKER_TAG} .
    - docker push ${CI_REGISTRY_IMAGE}:${DOCKER_TAG}
