version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  develop:
    jobs:
      - heroku/deploy-via-git:
          api-key: HEROKU_API_KEY
          app-name: $HEROKU_APP_NAME
          branch: develop
