version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

executors:
  docker-executor:
    docker:
      - image: cimg/base:stable
        auth:
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  preparing-environment:
    executor: docker-executor
    steps:
      - checkout
      - run: echo "DATABASE_URI=$DATABASE_URI" >> .env
      - run: cat .env

workflows:
  dev-heroku-deploy:
    jobs:
      - heroku/deploy-via-git:
          context: develop
          pre-deploy:
            - run: echo "DATABASE_URI=$DATABASE_URI" >> .env
            - run: cat .env
          api-key: HEROKU_API_KEY
          app-name: $HEROKU_APP_NAME
          branch: develop
