version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  dev-heroku-deploy:
    jobs:
      - heroku/deploy-via-git:
          context: develop
          pre-deploy:
            - run: echo "DATABASE_URI=$DATABASE_URI" >> .env
            - run: cat .env
          api-key: HEROKU_API_KEY
          app-name: $HEROKU_APP_NAME
          branch: develop
