version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  dev-heroku-deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - develop
          api-key: HEROKU_API_KEY
          app-name: actedu-act-api-dev
          branch: develop
  hml-heroku-deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - release*
          api-key: HEROKU_API_KEY
          app-name: actedu-act-api-hml
          branch: release*
  heroku-deploy:
    jobs:
      - heroku/deploy-via-git:
          filters:
            branches:
              only:
                - main
          api-key: HEROKU_API_KEY
          app-name: actedu-act-api
          branch: main
